### ISSUE TITLE
expected AffirmPhone

### ISSUE THREAD

**Issue by devgas** [Affirm/Magento_Affirm#14]
Hi, i am getting error: 
{"status_code": 400, "message": "expected AffirmPhone", "code": "invalid_field", "type": "invalid_request", "field": "billing.phone_number.phone_number"}

POST (request:
api_version v2
billing[address][city]  hgf
billing[address][country]   US
billing[address][line1] Some Str 3
billing[address][line2] 
billing[address][state] California
billing[address][zipcode]   95131
billing[email]  pavlrtfhot@****_.com
billing[name][full] Jhon Smith
billing[phone_number]   412354654
checkout_id 100002956
config[financial_product_...    SW1JYWC9ZV87UXJB
config[required_billing_f...    name,address,email
currency    USD
ioBB  
items[at004471][display_n...    Cr*********et
items[at004471][item_imag...    http://t********t/media/catalog/product/cache/1/image/265x/9df78eab33525d08d6e5fb8d27136e95/4/4/4471-1-l.jpg
items[at004471][item_url]   http://t**_****_t/plasma-tv-lift
items[at004471][qty]    1
items[at004471][sku]    at004471
items[at004471][unit_pric...    259900
items[at006196wht][displa...    Ca*********inet
items[at006196wht][item_i...    http://t********t/media/catalog/product/cache/1/image/265x/9df78eab33525d08d6e5fb8d27136e95/6/1/6196wht-1.jpg
items[at006196wht][item_u...    http://t********t/plasma-tv-lift
items[at006196wht][qty] 1
items[at006196wht][sku] at**_**ht
items[at006196wht][unit_p...    179900
merchant[charge_declined_...    http://t*******_t/checkout/onepage/
merchant[public_api_key]    *_************************
merchant[user_cancel_url]   http://t*******_t/checkout/onepage/
merchant[user_confirmatio...    http://t**_****_t/affirm/payment/confirm/
meta[__affirm_tracking_uu...    24**_*******a50
meta[release]   true
meta[source][client_name]   magento_affirm
meta[source][data][is_log...    false
meta[source][data][magent...    1.9.0.1
meta[source][version][0]    2.0.10
meta[user_timezone] Europe/Helsinki
shipping[address][city] hgf
shipping[address][country...    US
shipping[address][line1]    Some Str 3
shipping[address][line2]  
shipping[address][state]    California
shipping[address][zipcode...    95131
shipping[name][full]    Jhon Smith
shipping[phone_number]  412354654
shipping_amount 0
shipping_type   freeshipping_freeshipping
tax_amount  0
total   439800
);

API URL: https://api.affirm.com
 Affirm_Affirm - 2.0.10 version (for Magento)

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #13962 ( https://affirm.desk.com/web/agent/case/13962 )

Affirm | Apr 25, 2017 09:07PM UTC

------------------------------------------------------------------------------------------------------------
Case #13962
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] expected AffirmPhone (#14)
------------------------------------------------------------------------------------------------------------
Case Information (13962):

Subject: Re: [Affirm/Magento_Affirm] expected AffirmPhone (#14)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at APR 25, 2017 | 02:07PM PDT:
Closed #14.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/issues/14#event-1057446227

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #13962
------------------------------------------------------------------------------------------------------------
