### ISSUE TITLE
js error on product listing and product page if As Low As is disabled

### ISSUE THREAD

**Issue by ebaschiera** [Affirm/Magento_Affirm#28]
Hi,
if As Low As functionality is disabled in PDP and PLP, I get the following JS error: `Uncaught TypeError: AFFIRM_AFFIRM.promos.initLimitation is not a function`
This happens because of this call: https://github.com/Affirm/Magento_Affirm/blob/master/extension/app/design/frontend/base/default/template/affirm/promo/aslowas/list.phtml#L6

Thanks!

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #14063 ( https://affirm.desk.com/web/agent/case/14063 )

Affirm | Apr 27, 2017 08:18AM UTC

------------------------------------------------------------------------------------------------------------
Case #14063
Customer: Affirm/Magento_Affirm
Subject: [Affirm/Magento_Affirm] js error on product listing and product page if As Low As is disabled (#28)
------------------------------------------------------------------------------------------------------------
Case Information (14063):

Subject: [Affirm/Magento_Affirm] js error on product listing and product page if As Low As is disabled (#28)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at APR 27, 2017 | 01:18AM PDT:
Hi,
if As Low As functionality is disabled in PDP and PLP, I get the following JS error: `Uncaught TypeError: AFFIRM_AFFIRM.promos.initLimitation is not a function`
This happens because of this call: https://github.com/Affirm/Magento_Affirm/blob/master/extension/app/design/frontend/base/default/template/affirm/promo/aslowas/list.phtml#L6

Thanks!

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/issues/28

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #14063
------------------------------------------------------------------------------------------------------------

**Comment by diptib10** [comment]
Resolved with [v3.4.1](https://github.com/Affirm/Magento_Affirm/releases/tag/v3.4.1)
